version: '3.9'
services:
    node-frontend:
        container_name: frontend
        build: ./Frontend
        ports:
            - "5173:5173"

    node-server:
        container_name: server
        build: ./Backend
        ports:
            - "8000:8000"

    db:
        image: mysql:latest
        container_name: db
        # env_file: ./Backend/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_password}
            MYSQL_DATABASE: ${DB_database}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        # env_file: ./Backend/.env
        environment:
            PMA_HOST: ${DB_host}
            PMA_PORT: ${DB_port}
            PMA_USER: ${DB_user}
            PMA_PASSWORD: ${DB_password}
        ports:
            - "8080:80"
        depends_on:
            - db

    stripe-listener:
        image: stripe/stripe-cli:latest
        container_name: stripe-listener
        env_file: /Backend/.env
        environment:
            - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
        command: [ "listen", "--forward-to", "localhost:8000/webhook" ]
        network_mode: "host"
        depends_on:
            - node-server

    model:
        container_name: model
        build: ./Model
        ports:
            - "5555:5555"

volumes:
    db_data:
